### ISSUE TITLE
Unable to install snap: not supported

### ISSUE THREAD

**Issue by Aikatsui** [popey/session-desktop-snap#2]
**Describe the bug**
Unable to install session stable or edge

**To Reproduce**
Go to https://snapcraft.io/session-desktop --> install --> view in desktop store

**Screenshots or Logs**
![Screenshot from 2021-08-17 15-48-04](https://user-images.githubusercontent.com/63988538/129683252-8eb12e03-de38-4d0b-9958-fa1a7a5bb651.png)

**Other information (please complete the following information):**

* OS: Ubuntu 20.04.2/ 21.04
* Session Version: stable/edge (snap)

**Comment by Aikatsui** [comment]
https://github.com/oxen-io/session-desktop-temp/issues/603

**Comment by popey** [comment]
Fixed
