### ISSUE TITLE
camera doesn't work

### ISSUE THREAD

**Issue by stsp** [popey/session-desktop-snap#5]
I installed session-desktop from snap,
and the camera isn't working during the
call. Yes, I enabled the video calls beta
feature. But it says "camera not found".

I then downloaded the software directly
from getsession.org, and there camera
works. So its a snap-related problem.

**Comment by popey** [comment]
Thanks for filing the issue.

A new build is in the candidate channel, which should work.

`snap refresh session-desktop --candidate`

`snap connect session-desktop:camera`

Let me know if that works for you!

**Comment by stsp** [comment]
Thank you. :)
That seems to work now.
Strange that no one else have noticed.
